### ISSUE TITLE
Shader is upside down

### ISSUE THREAD

**Issue by SolsticeSpectrum** [GabeRundlett/desktop-shadertoy#14]
This shader for some reason gets imported upside down
https://www.shadertoy.com/view/wtS3W3

**Comment by GabeRundlett** [comment]
![image](https://github.com/user-attachments/assets/a7433028-90b2-4e0e-8d51-9559139981e0)

impressive. I will look into this one for sure. Very interested

**Comment by GabeRundlett** [comment]
Found the issue. For context, Vulkan's coordinate system is upside-down compared to OpenGL's. Desktop Shadertoy uses Vulkan, and Shadertoy uses WebGL (essentially just OpenGL on the web). I was already very aware of this issue, but I fixed it in a slightly strange way. When rendering the final "Image" pass, the input `fragCoord` parameter is flipped. This is problematic specifically for this shadertoy because they don't use the `fragCoord` variable, and instead just use the OpenGL intrinsic variable `gl_FragCoord.xy`.

Instead of doing this weird way of flipping the final image, I instead now flip the whole thing after the fact when blitting to the swapchain. Fixed in https://github.com/GabeRundlett/desktop-shadertoy/commit/027e669afb7ab6d6096ac87dce4ab7f35a74a0d9
