### ISSUE TITLE
Compiling from source

### ISSUE THREAD

**Issue by danjgill** [GabeRundlett/desktop-shadertoy#16]
Hi Gabe,

First of all, thank you for such a wonderful program. It loads and displays many shadertoys that many other programs on the internet cannot. Impressive work.

So I am running the desktop-shadertoy.exe under Windows, and that works fine. Does exactly what it says it will do.

However, I was trying to compile the code myself, to better understand it, and ran into all sorts of problems. Here is what I did:

mkdir build

cmake -S . -B build

This finds some of the requirements, but usually bombs out on something. So I clone the missing package from github, and compile it, which gets me a bit further, but inevitably I find I am missing some needed .cmake file for one of the packages.

Can you provide any advice here? If it were to "git clone" the desktop-shadertoy repository, which commands would I need to

a) install all the dependancies
b) get cmake to generate a proper config, and
c) compile a usable EXE

Sorry for the noob question, but I have been struggling with this for a couple of days now, and figured it would be easier to go straight to the source.

Thanks for any direction you can provide.

**Comment by GabeRundlett** [comment]
Hi @danjgill. Desktop Shadertoy has a few dependencies, and the intended way of retrieving those is via the vcpkg package manager. The CMake is set up to use vcpkg automatically if you configure CMake with the added define `-DDESKTOP_SHADERTOY_USE_VCPKG=true`, which is automatically set if you use the CMake preset feature by running `cmake --preset=<insert-preset>` such as `cmake --preset=cl-x86_64-windows-msvc` to compile with CL.exe on Windows.

This configuration step may take a little while to run because I haven't been to careful about which packages I use for this project, and vcpkg will compile all the dependencies from scratch. Once the configure step is done, you can compile it with presets as well like so `cmake --build --preset=cl-x86_64-windows-msvc-release` (you can also choose debug instead)

**Comment by GabeRundlett** [comment]
If instead you're used to Visual Studio solutions, you can create those with a preset as well, `cmake --preset=vs-x86_64-windows-msvc`. Otherwise, I recommend using vscode and the c++/cmake-tools extensions to be able to do all this from the UI

**Comment by danjgill** [comment]
Wow! That was a quick response! :-)

I will give this a try and post here if I am successful.

Thanks again for the wonderful program.

**Comment by danjgill** [comment]
Hi

Just a note to say that I was successful with the instructions you provided. It is up and running in the debugger even as I type this.

Can I suggest that some version of these instructions be included in the README for this project? I certainly helped me.

Thanks again.
